import jsPDF from 'jspdf';

interface ReportMetrics {
  totalRevenue: string
  newCustomers: string
  activeAccounts: string
  growthRate: string
  revenueMoM: string
  customersMoM: string
  accountsMoM: string
  growthMoM: string
}

export function generatePDFReport(metrics: ReportMetrics) {
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(20);
  doc.text('Dashboard Report', pageW / 2, 20, { align: 'center' });

  // Date
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, pageW / 2, 28, { align: 'center' });

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 34, pageW - 14, 34);

  // KPIs
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Key Metrics', 14, 44);

  const kpis = [
    { label: 'Total Revenue', value: metrics.totalRevenue, change: metrics.revenueMoM },
    { label: 'New Customers', value: metrics.newCustomers, change: metrics.customersMoM },
    { label: 'Active Accounts', value: metrics.activeAccounts, change: metrics.accountsMoM },
    { label: 'Growth Rate', value: metrics.growthRate, change: metrics.growthMoM },
  ];

  kpis.forEach((kpi, i) => {
    const y = 54 + i * 22;
    // Card background
    doc.setFillColor(248, 250, 252);
    doc.rect(14, y - 6, pageW - 28, 18, 'F');
    // Label
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(kpi.label, 18, y);
    // Value
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(kpi.value, 18, y + 7);
    // Change
    doc.setFontSize(9);
    const isUp = !kpi.change.startsWith('-');
    doc.setTextColor(isUp ? 34 : 220, isUp ? 197 : 38, isUp ? 94 : 38);
    doc.text(`${isUp ? '▲' : '▼'} ${kpi.change}`, pageW - 18, y + 3, { align: 'right' });
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(7);
    doc.text('vs last month', pageW - 18, y + 9, { align: 'right' });
  });

  // Second divider
  const chartY = 54 + kpis.length * 22 + 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, chartY, pageW - 14, chartY);

  // Chart Section
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Summary', chartY + 10, 14);

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  const summaryLines = [
    'This report provides an overview of key business metrics for the current period.',
    'All figures are compared against the previous month for trend analysis.',
    '',
    '• Revenue continues to trend upward, driven by new customer acquisition.',
    '• Active accounts show strong retention with minimal churn.',
    '• Growth rate meets quarterly projections.',
    '• New customer acquisition needs attention in specific segments.',
  ];
  summaryLines.forEach((line, i) => {
    doc.text(line, 14, chartY + 20 + i * 6);
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Dashboard — For internal use only', pageW / 2, 285, { align: 'center' });

  doc.save(`dashboard-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
