'use client';

import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';

const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.overview': 'Overview',
    'nav.products': 'Products',
    'nav.users': 'Users',
    'nav.kanban': 'Kanban',
    'nav.chat': 'Chat',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    'nav.workspaces': 'Workspaces',
    'nav.billing': 'Billing',
    'nav.exclusive': 'Exclusive',
    'nav.profile': 'Profile',
    'nav.reports': 'Reports',
    'nav.group.overview': 'Overview',
    'nav.group.elements': 'Elements',
    'nav.item.dashboard': 'Dashboard',
    'nav.item.workspaces': 'Workspaces',
    'nav.item.teams': 'Teams',
    'nav.item.product': 'Product',
    'nav.item.users': 'Users',
    'nav.item.kanban': 'Kanban',
    'nav.item.chat': 'Chat',
    'nav.item.reports': 'Reports',
    'nav.item.forms': 'Forms',
    'nav.item.basicForm': 'Basic Form',
    'nav.item.multiStepForm': 'Multi-Step Form',
    'nav.item.sheetDialog': 'Sheet & Dialog',
    'nav.item.advancedPatterns': 'Advanced Patterns',
    'nav.item.reactQuery': 'React Query',
    'nav.item.icons': 'Icons',
    'nav.item.pro': 'Pro',
    'nav.item.exclusive': 'Exclusive',
    'nav.item.account': 'Account',
    'nav.item.profile': 'Profile',
    'nav.item.notifications': 'Notifications',
    'nav.item.billing': 'Billing',
    'nav.item.login': 'Login',

    // Overview
    'overview.title': 'Overview',
    'overview.welcome': 'Hi, Welcome back 👋',
    'overview.totalRevenue': 'Total Revenue',
    'overview.newCustomers': 'New Customers',
    'overview.activeAccounts': 'Active Accounts',
    'overview.growthRate': 'Growth Rate',
    'overview.subscriptions': 'Subscriptions',
    'overview.sales': 'Sales',
    'overview.activeNow': 'Active Now',
    'overview.recentSales': 'Recent Sales',
    'overview.salesThisMonth': 'You made 265 sales this month.',
    'overview.download': 'Download',
    'overview.trendingUp': 'Trending up this month',
    'overview.visitors6m': 'Visitors for the last 6 months',
    'overview.down20': 'Down 20% this period',
    'overview.acquisitionNeeds': 'Acquisition needs attention',
    'overview.strongRetention': 'Strong user retention',
    'overview.engagementExceed': 'Engagement exceed targets',
    'overview.steadyPerformance': 'Steady performance increase',
    'overview.meetsProjections': 'Meets growth projections',
    'overview.barChartTitle': 'Bar Chart - Multiple',
    'overview.barChartDesc': 'Monthly desktop vs mobile',
    'overview.areaChartTitle': 'Dotted Area Chart',
    'overview.areaChartDesc': 'Showing total visitors for the period',
    'overview.pieChartTitle': 'Pie Chart',
    'overview.pieChartDesc': 'Browser distribution',
    'overview.vsLastMonth': 'vs last month',
    'overview.vsLastYear': 'vs last year',
    'overview.adminViewDesc': 'You see summary KPI cards and charts.',
    'overview.managerViewDesc': 'You see detailed transaction data.',
    'overview.chart.desktop': 'Desktop',
    'overview.chart.mobile': 'Mobile',
    'overview.chart.chrome': 'Chrome',
    'overview.chart.safari': 'Safari',
    'overview.chart.firefox': 'Firefox',
    'overview.chart.edge': 'Edge',
    'overview.chart.other': 'Other',

    // Common
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.loading': 'Loading...',
    'common.noResults': 'No results found',
    'common.actions': 'Actions',
    'common.noAccess': 'You do not have access to this page.',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.back': 'Back',
    'common.update': 'Update',
    'common.viewAll': 'View All',
    'common.from': 'From',
    'common.to': 'To',
    'common.confirm': 'Confirm',
    'common.avatar': 'Avatar',

    // User
    'user.profile': 'Profile',
    'user.billing': 'Billing',
    'user.settings': 'Settings',
    'user.newTeam': 'New Team',
    'user.signOut': 'Sign Out',
    'user.notifications': 'Notifications',
    'user.firstName': 'First Name',
    'user.lastName': 'Last Name',
    'user.email': 'Email',
    'user.phone': 'Phone',
    'user.role': 'Role',
    'user.status': 'Status',
    'user.firstNamePlaceholder': 'John',
    'user.lastNamePlaceholder': 'Doe',
    'user.emailPlaceholder': 'john@example.com',
    'user.phonePlaceholder': '(555) 123-4567',
    'user.rolePlaceholder': 'Select role',
    'user.statusPlaceholder': 'Select status',
    'user.add': 'Add User',
    'user.edit': 'Edit User',
    'user.new': 'New User',
    'user.editDesc': 'Update the user details below.',
    'user.newDesc': 'Fill in the details to create a new user.',
    'user.updateUser': 'Update User',
    'user.createUser': 'Create User',
    'user.created': 'User created successfully',
    'user.createFailed': 'Failed to create user',
    'user.updated': 'User updated successfully',
    'user.updateFailed': 'Failed to update user',
    'user.deleted': 'User deleted successfully',
    'user.deleteFailed': 'Failed to delete user',

    // Language
    'lang.switch': 'Switch Language',
    'lang.en': 'English',
    'lang.zh': '中文',

    // Date
    'date.7d': 'Last 7 days',
    'date.30d': 'Last 30 days',
    'date.90d': 'Last 90 days',
    'date.1y': 'This year',
    'date.all': 'All time',

    // Services & Orders
    'services.price': 'Price',
    'orders.orderId': 'Order ID',
    'orders.date': 'Date',

    // Data Table
    'table.noResults': 'No results.',
    'table.rowsSelected': '{selected} of {total} row(s) selected.',
    'table.rowsTotal': '{total} row(s) total.',
    'table.rowsPerPage': 'Rows per page',
    'table.pageOf': 'Page {page} of {total}',
    'table.asc': 'Asc',
    'table.desc': 'Desc',
    'table.reset': 'Reset',
    'table.hide': 'Hide',
    'table.selected': '{size} selected',
    'table.noResultsFound': 'No results found.',
    'table.clearFilters': 'Clear filters',
    'table.view': 'View',
    'table.searchColumns': 'Search columns...',
    'table.noColumnsFound': 'No columns found.',
    'table.selectDateRange': 'Select date range',
    'table.selectDate': 'Select date',
    'table.clear': 'Clear',
    'table.goToFirstPage': 'Go to first page',
    'table.goToPreviousPage': 'Go to previous page',
    'table.goToNextPage': 'Go to next page',
    'table.goToLastPage': 'Go to last page',
    'table.toggleColumns': 'Toggle columns',
    'table.resetFilters': 'Reset filters',

    // Data Table Operators
    'operator.contains': 'Contains',
    'operator.doesNotContain': 'Does not contain',
    'operator.is': 'Is',
    'operator.isNot': 'Is not',
    'operator.isEmpty': 'Is empty',
    'operator.isNotEmpty': 'Is not empty',
    'operator.isLessThan': 'Is less than',
    'operator.isLessThanOrEqual': 'Is less than or equal to',
    'operator.isGreaterThan': 'Is greater than',
    'operator.isGreaterThanOrEqual': 'Is greater than or equal to',
    'operator.isBetween': 'Is between',
    'operator.isBefore': 'Is before',
    'operator.isAfter': 'Is after',
    'operator.isOnOrBefore': 'Is on or before',
    'operator.isOnOrAfter': 'Is on or after',
    'operator.isRelativeToToday': 'Is relative to today',
    'operator.hasAnyOf': 'Has any of',
    'operator.hasNoneOf': 'Has none of',

    // Pages
    'page.products.title': 'Products',
    'page.products.desc': 'Manage products and inventory',
    'page.users.title': 'Users',
    'page.users.desc': 'Manage users and their roles',
    'page.kanban.title': 'Kanban',
    'page.kanban.desc': 'Manage tasks with drag and drop',
    'page.notifications.title': 'Notifications',
    'page.notifications.desc': 'View and manage your notifications',
    'page.workspaces.title': 'Workspaces',
    'page.workspaces.desc': 'Manage your workspaces and teams',
    'page.billing.title': 'Billing & Plans',
    'page.billing.desc': 'Choose a plan that works for you',
    'page.forms.basic.title': 'Basic Form',
    'page.forms.basic.desc': 'A comprehensive form demo',
    'page.forms.multiStep.title': 'Multi-Step Form',
    'page.forms.multiStep.desc': 'Multi-step wizard form with validation',
    'page.forms.sheet.title': 'Sheet & Dialog Forms',
    'page.forms.sheet.desc': 'Forms displayed in sheet and dialog overlays',
    'page.forms.advanced.title': 'Advanced Form Patterns',
    'page.forms.advanced.desc': 'Complex form patterns with dynamic fields',
    'page.reactQuery.title': 'React Query',
    'page.reactQuery.desc': 'React Query data fetching demos',
    'page.icons.title': 'Icons',
    'page.icons.desc': 'Browse Tabler Icons library',
    'page.exclusive.title': 'Exclusive Area',
    'page.exclusive.desc': 'Premium content for Pro subscribers',

    // Product
    'product.add': 'Add New',
    'product.image': 'Product Image',
    'product.imageDesc': 'Upload a product image',
    'product.name': 'Product Name',
    'product.namePlaceholder': 'Enter product name',
    'product.category': 'Category',
    'product.categoryPlaceholder': 'Select category',
    'product.price': 'Price',
    'product.pricePlaceholder': 'Enter price',
    'product.description': 'Description',
    'product.descriptionPlaceholder': 'Enter product description',
    'product.update': 'Update Product',
    'product.addProduct': 'Add Product',
    'product.back': 'Back',
    'product.created': 'Product created successfully',
    'product.createFailed': 'Failed to create product',
    'product.updated': 'Product updated successfully',
    'product.updateFailed': 'Failed to update product',
    'product.deleted': 'Product deleted successfully',
    'product.deleteFailed': 'Failed to delete product',

    // Categories
    'category.electronics': 'Electronics',
    'category.furniture': 'Furniture',
    'category.clothing': 'Clothing',
    'category.books': 'Books',
    'category.sports': 'Sports & Outdoors',
    'category.home': 'Home & Garden',
    'category.toys': 'Toys',
    'category.food': 'Food & Beverages',
    'category.beauty': 'Beauty Products',

    // Roles
    'role.developer': 'Developer',
    'role.designer': 'Designer',
    'role.manager': 'Manager',
    'role.admin': 'Admin',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.invited': 'Invited',

    // Kanban
    'kanban.backlog': 'Backlog',
    'kanban.inProgress': 'In Progress',
    'kanban.review': 'Review',
    'kanban.done': 'Done',
    'kanban.addTask': 'Add New Task',
    'kanban.newTask': 'Add New Task',
    'kanban.taskQuestion': 'What do you want to get done today?',
    'kanban.taskPlaceholder': 'Task title...',
    'kanban.descPlaceholder': 'Description...',
    'kanban.add': 'Add Task',

    // Chat
    'chat.messenger': 'Messenger',
    'chat.activeConversations': '{count} active conversations',
    'chat.live': 'Live',
    'chat.searchConversations': 'Search conversations',
    'chat.noConversations': 'No conversations found',
    'chat.noMessages': 'No messages yet',
    'chat.online': 'Online',
    'chat.offline': 'Offline',
    'chat.audioCall': 'Start audio call',
    'chat.videoCall': 'Start video call',
    'chat.openMenu': 'Open conversation menu',
    'chat.writeMessage': 'Write a message',
    'chat.messageHint': 'Message {name} (Enter to send, Shift+Enter for newline)',
    'chat.sendMessage': 'Send message',
    'chat.attachFile': 'Attach a file',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.new': '{count} new',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.empty': 'No notifications yet',
    'notifications.pageEmpty': 'No notifications',
    'notifications.tabAll': 'All',
    'notifications.tabUnread': 'Unread',
    'notifications.tabRead': 'Read',

    // Auth
    'auth.login': 'Login',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'Enter your email...',
    'auth.continueWithEmail': 'Continue With Email',
    'auth.orContinueWith': 'Or continue with',
    'auth.starOnGitHub': 'Star on GitHub',
    'auth.byClickingContinue': 'By clicking continue, you agree to our',
    'auth.termsOfService': 'Terms of Service',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.description':
      'This starter template provides a modern admin dashboard with multi-tenant support, billing, and more.',

    // Billing & Exclusive
    'billing.noOrg': 'No Organization Selected',
    'billing.noOrgDesc': 'Please select or create an organization to manage billing.',
    'billing.availablePlans': 'Available Plans',
    'billing.choosePlan': 'Choose a plan that works for you.',
    'exclusive.proRequired': 'Pro Plan Required',
    'exclusive.proRequiredDesc': 'This page is only available to Pro plan subscribers.',
    'exclusive.upgrade': 'Upgrade your subscription to access the exclusive features.',
    'exclusive.welcome': 'Welcome to the Exclusive Area!',
    'exclusive.thankYou': 'Thank you for being a Pro subscriber.',

    // Forms demo
    'form.demo.title': 'All Form Inputs Demo',
    'form.demo.textInputs': 'Text Inputs',
    'form.demo.selectCombobox': 'Select & Combobox',
    'form.demo.checkboxRadio': 'Checkbox & Radio',
    'form.demo.toggleSwitch': 'Toggle & Switch',
    'form.demo.slider': 'Slider',
    'form.demo.dateTime': 'Date & Time',
    'form.demo.specialInputs': 'Special Inputs',
    'form.demo.fileUpload': 'File Upload',
    'form.demo.formDataPreview': 'Form Data Preview',
    'form.demo.submitForm': 'Submit Form',
    'form.multiStep.basicInfo': 'Basic Info',
    'form.multiStep.details': 'Details',
    'form.multiStep.reviewSubmit': 'Review & Submit',
    'form.advanced.teamRegistration': 'Team Registration',
    'form.advanced.account': 'Account',
    'form.advanced.teamInfo': 'Team Info',
    'form.advanced.members': 'Members',
    'form.advanced.preferences': 'Preferences',
    'form.sheet.sheetForm': 'Sheet Form',
    'form.sheet.dialogForm': 'Dialog Form',
    'form.sheet.toastNotifications': 'Toast Notifications',

    // Icons page
    'icons.searchPlaceholder': 'Search icons...',
    'icons.browse': 'Browse Tabler Icons',
    'icons.noResults': 'No icons found matching "{query}".'
  },
  zh: {
    // Navigation
    'nav.dashboard': '仪表板',
    'nav.overview': '概览',
    'nav.products': '产品',
    'nav.users': '用户',
    'nav.kanban': '看板',
    'nav.chat': '聊天',
    'nav.notifications': '通知',
    'nav.settings': '设置',
    'nav.workspaces': '工作区',
    'nav.billing': '计费',
    'nav.exclusive': '专属',
    'nav.profile': '个人资料',
    'nav.reports': '报表',
    'nav.group.overview': '概览',
    'nav.group.elements': '元素',
    'nav.item.dashboard': '仪表板',
    'nav.item.workspaces': '工作区',
    'nav.item.teams': '团队',
    'nav.item.product': '产品',
    'nav.item.users': '用户',
    'nav.item.kanban': '看板',
    'nav.item.chat': '聊天',
    'nav.item.reports': '报表',
    'nav.item.forms': '表单',
    'nav.item.basicForm': '基础表单',
    'nav.item.multiStepForm': '多步表单',
    'nav.item.sheetDialog': '抽屉与对话框',
    'nav.item.advancedPatterns': '高级模式',
    'nav.item.reactQuery': 'React Query',
    'nav.item.icons': '图标',
    'nav.item.pro': '专业版',
    'nav.item.exclusive': '专属',
    'nav.item.account': '账户',
    'nav.item.profile': '个人资料',
    'nav.item.notifications': '通知',
    'nav.item.billing': '计费',
    'nav.item.login': '登录',

    // Overview
    'overview.title': '概览',
    'overview.welcome': '你好，欢迎回来 👋',
    'overview.totalRevenue': '总收入',
    'overview.newCustomers': '新增客户',
    'overview.activeAccounts': '活跃账户',
    'overview.growthRate': '增长率',
    'overview.subscriptions': '订阅数',
    'overview.sales': '销售额',
    'overview.activeNow': '当前在线',
    'overview.recentSales': '近期销售',
    'overview.salesThisMonth': '您本月完成了 265 笔销售。',
    'overview.download': '下载',
    'overview.trendingUp': '本月呈上升趋势',
    'overview.visitors6m': '过去 6 个月的访客',
    'overview.down20': '本期下降 20%',
    'overview.acquisitionNeeds': '客户获取需要关注',
    'overview.strongRetention': '用户留存强劲',
    'overview.engagementExceed': '参与度超出预期',
    'overview.steadyPerformance': '性能稳步提升',
    'overview.meetsProjections': '符合增长预期',
    'overview.barChartTitle': '柱状图 - 多组数据',
    'overview.barChartDesc': '桌面端 vs 移动端月度对比',
    'overview.areaChartTitle': '面积图',
    'overview.areaChartDesc': '显示该时段的总访问量',
    'overview.pieChartTitle': '饼图',
    'overview.pieChartDesc': '浏览器分布',
    'overview.vsLastMonth': '环比上月',
    'overview.vsLastYear': '同比去年',
    'overview.adminViewDesc': '您看到的是汇总KPI卡片和图表。',
    'overview.managerViewDesc': '您看到的是详细交易数据。',
    'overview.chart.desktop': '桌面端',
    'overview.chart.mobile': '移动端',
    'overview.chart.chrome': 'Chrome',
    'overview.chart.safari': 'Safari',
    'overview.chart.firefox': 'Firefox',
    'overview.chart.edge': 'Edge',
    'overview.chart.other': '其他',

    // Common
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.export': '导出',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.create': '创建',
    'common.loading': '加载中...',
    'common.noResults': '暂无结果',
    'common.actions': '操作',
    'common.noAccess': '您没有访问此页面的权限。',
    'common.submit': '提交',
    'common.reset': '重置',
    'common.next': '下一步',
    'common.previous': '上一步',
    'common.back': '返回',
    'common.update': '更新',
    'common.viewAll': '查看全部',
    'common.from': '从',
    'common.to': '至',
    'common.confirm': '确认',
    'common.avatar': '头像',

    // User
    'user.profile': '个人资料',
    'user.billing': '计费',
    'user.settings': '设置',
    'user.newTeam': '新建团队',
    'user.signOut': '退出登录',
    'user.notifications': '通知',
    'user.firstName': '名',
    'user.lastName': '姓',
    'user.email': '邮箱',
    'user.phone': '电话',
    'user.role': '角色',
    'user.status': '状态',
    'user.firstNamePlaceholder': '请输入名',
    'user.lastNamePlaceholder': '请输入姓',
    'user.emailPlaceholder': 'user@example.com',
    'user.phonePlaceholder': '138-0000-0000',
    'user.rolePlaceholder': '请选择角色',
    'user.statusPlaceholder': '请选择状态',
    'user.add': '添加用户',
    'user.edit': '编辑用户',
    'user.new': '新建用户',
    'user.editDesc': '请在下方更新用户信息。',
    'user.newDesc': '请填写信息以创建新用户。',
    'user.updateUser': '更新用户',
    'user.createUser': '创建用户',
    'user.created': '用户创建成功',
    'user.createFailed': '用户创建失败',
    'user.updated': '用户更新成功',
    'user.updateFailed': '用户更新失败',
    'user.deleted': '用户删除成功',
    'user.deleteFailed': '用户删除失败',

    // Language
    'lang.switch': '切换语言',
    'lang.en': 'English',
    'lang.zh': '中文',

    // Date
    'date.7d': '近7天',
    'date.30d': '近30天',
    'date.90d': '近90天',
    'date.1y': '今年',
    'date.all': '全部',

    // Services & Orders
    'services.price': '价格',
    'orders.orderId': '订单编号',
    'orders.date': '日期',

    // Data Table
    'table.noResults': '暂无数据。',
    'table.rowsSelected': '已选择 {selected} / {total} 行。',
    'table.rowsTotal': '共 {total} 行。',
    'table.rowsPerPage': '每页行数',
    'table.pageOf': '第 {page} 页，共 {total} 页',
    'table.asc': '升序',
    'table.desc': '降序',
    'table.reset': '重置',
    'table.hide': '隐藏',
    'table.selected': '已选 {size} 项',
    'table.noResultsFound': '未找到结果。',
    'table.clearFilters': '清除筛选',
    'table.view': '显示',
    'table.searchColumns': '搜索列...',
    'table.noColumnsFound': '未找到列。',
    'table.selectDateRange': '选择日期范围',
    'table.selectDate': '选择日期',
    'table.clear': '清除',
    'table.goToFirstPage': '首页',
    'table.goToPreviousPage': '上一页',
    'table.goToNextPage': '下一页',
    'table.goToLastPage': '末页',
    'table.toggleColumns': '切换列',
    'table.resetFilters': '重置筛选',

    // Data Table Operators
    'operator.contains': '包含',
    'operator.doesNotContain': '不包含',
    'operator.is': '等于',
    'operator.isNot': '不等于',
    'operator.isEmpty': '为空',
    'operator.isNotEmpty': '不为空',
    'operator.isLessThan': '小于',
    'operator.isLessThanOrEqual': '小于等于',
    'operator.isGreaterThan': '大于',
    'operator.isGreaterThanOrEqual': '大于等于',
    'operator.isBetween': '介于',
    'operator.isBefore': '早于',
    'operator.isAfter': '晚于',
    'operator.isOnOrBefore': '当天或早于',
    'operator.isOnOrAfter': '当天或晚于',
    'operator.isRelativeToToday': '相对今天',
    'operator.hasAnyOf': '包含任一',
    'operator.hasNoneOf': '不包含任一',

    // Pages
    'page.products.title': '产品管理',
    'page.products.desc': '管理产品和库存',
    'page.users.title': '用户管理',
    'page.users.desc': '管理用户及其角色',
    'page.kanban.title': '看板',
    'page.kanban.desc': '通过拖拽管理任务',
    'page.notifications.title': '通知',
    'page.notifications.desc': '查看和管理通知',
    'page.workspaces.title': '工作区',
    'page.workspaces.desc': '管理工作区和团队',
    'page.billing.title': '计费与套餐',
    'page.billing.desc': '选择适合您的套餐',
    'page.forms.basic.title': '基础表单',
    'page.forms.basic.desc': '综合表单演示',
    'page.forms.multiStep.title': '多步表单',
    'page.forms.multiStep.desc': '带验证的多步向导表单',
    'page.forms.sheet.title': '抽屉与对话框表单',
    'page.forms.sheet.desc': '在抽屉和对话框中展示表单',
    'page.forms.advanced.title': '高级表单模式',
    'page.forms.advanced.desc': '含动态字段的复杂表单模式',
    'page.reactQuery.title': 'React Query',
    'page.reactQuery.desc': 'React Query 数据获取演示',
    'page.icons.title': '图标',
    'page.icons.desc': '浏览 Tabler 图标库',
    'page.exclusive.title': '专属区域',
    'page.exclusive.desc': '专业版用户的专属内容',

    // Product
    'product.add': '新增',
    'product.image': '产品图片',
    'product.imageDesc': '上传产品图片',
    'product.name': '产品名称',
    'product.namePlaceholder': '请输入产品名称',
    'product.category': '分类',
    'product.categoryPlaceholder': '请选择分类',
    'product.price': '价格',
    'product.pricePlaceholder': '请输入价格',
    'product.description': '产品描述',
    'product.descriptionPlaceholder': '请输入产品描述',
    'product.update': '更新产品',
    'product.addProduct': '添加产品',
    'product.back': '返回',
    'product.created': '产品创建成功',
    'product.createFailed': '产品创建失败',
    'product.updated': '产品更新成功',
    'product.updateFailed': '产品更新失败',
    'product.deleted': '产品删除成功',
    'product.deleteFailed': '产品删除失败',

    // Categories
    'category.electronics': '电子产品',
    'category.furniture': '家具',
    'category.clothing': '服装',
    'category.books': '图书',
    'category.sports': '运动户外',
    'category.home': '家居园艺',
    'category.toys': '玩具',
    'category.food': '食品饮料',
    'category.beauty': '美妆个护',

    // Roles
    'role.developer': '开发人员',
    'role.designer': '设计师',
    'role.manager': '经理',
    'role.admin': '管理员',
    'status.active': '活跃',
    'status.inactive': '非活跃',
    'status.invited': '已邀请',

    // Kanban
    'kanban.backlog': '待办',
    'kanban.inProgress': '进行中',
    'kanban.review': '审查',
    'kanban.done': '完成',
    'kanban.addTask': '添加新任务',
    'kanban.newTask': '添加新任务',
    'kanban.taskQuestion': '今天想要完成什么？',
    'kanban.taskPlaceholder': '任务标题...',
    'kanban.descPlaceholder': '描述...',
    'kanban.add': '添加任务',

    // Chat
    'chat.messenger': '消息',
    'chat.activeConversations': '{count} 个活跃会话',
    'chat.live': '在线',
    'chat.searchConversations': '搜索会话',
    'chat.noConversations': '未找到会话',
    'chat.noMessages': '暂无消息',
    'chat.online': '在线',
    'chat.offline': '离线',
    'chat.audioCall': '发起语音通话',
    'chat.videoCall': '发起视频通话',
    'chat.openMenu': '打开会话菜单',
    'chat.writeMessage': '输入消息',
    'chat.messageHint': '向 {name} 发送消息（Enter 发送，Shift+Enter 换行）',
    'chat.sendMessage': '发送消息',
    'chat.attachFile': '附加文件',

    // Notifications
    'notifications.title': '通知',
    'notifications.new': '{count} 条新通知',
    'notifications.markAllRead': '全部标为已读',
    'notifications.empty': '暂无通知',
    'notifications.pageEmpty': '暂无通知',
    'notifications.tabAll': '全部',
    'notifications.tabUnread': '未读',
    'notifications.tabRead': '已读',

    // Auth
    'auth.login': '登录',
    'auth.signUp': '注册',
    'auth.email': '邮箱',
    'auth.emailPlaceholder': '请输入邮箱...',
    'auth.continueWithEmail': '继续使用邮箱',
    'auth.orContinueWith': '或使用以下方式继续',
    'auth.starOnGitHub': '在 GitHub 上点赞',
    'auth.byClickingContinue': '点击继续即表示您同意我们的',
    'auth.termsOfService': '服务条款',
    'auth.privacyPolicy': '隐私政策',
    'auth.description': '此模板提供现代化的管理后台，支持多租户、计费等更多功能。',

    // Billing & Exclusive
    'billing.noOrg': '未选择组织',
    'billing.noOrgDesc': '请选择或创建组织以管理计费。',
    'billing.availablePlans': '可用套餐',
    'billing.choosePlan': '选择适合您的套餐。',
    'exclusive.proRequired': '需要专业版套餐',
    'exclusive.proRequiredDesc': '此页面仅对专业版用户开放。',
    'exclusive.upgrade': '升级套餐以访问专属功能。',
    'exclusive.welcome': '欢迎来到专属区域！',
    'exclusive.thankYou': '感谢您成为专业版用户。',

    // Forms demo
    'form.demo.title': '所有表单输入演示',
    'form.demo.textInputs': '文本输入',
    'form.demo.selectCombobox': '选择与组合框',
    'form.demo.checkboxRadio': '复选框与单选',
    'form.demo.toggleSwitch': '开关与切换',
    'form.demo.slider': '滑块',
    'form.demo.dateTime': '日期与时间',
    'form.demo.specialInputs': '特殊输入',
    'form.demo.fileUpload': '文件上传',
    'form.demo.formDataPreview': '表单数据预览',
    'form.demo.submitForm': '提交表单',
    'form.multiStep.basicInfo': '基本信息',
    'form.multiStep.details': '详细信息',
    'form.multiStep.reviewSubmit': '确认并提交',
    'form.advanced.teamRegistration': '团队注册',
    'form.advanced.account': '账户信息',
    'form.advanced.teamInfo': '团队信息',
    'form.advanced.members': '成员',
    'form.advanced.preferences': '偏好设置',
    'form.sheet.sheetForm': '抽屉表单',
    'form.sheet.dialogForm': '对话框表单',
    'form.sheet.toastNotifications': '消息通知',

    // Icons page
    'icons.searchPlaceholder': '搜索图标...',
    'icons.browse': '浏览 Tabler 图标',
    'icons.noResults': '未找到包含 "{query}" 的图标。'
  }
};

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language | null;
    if (saved === 'en' || saved === 'zh') {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
  }, []);

  const t = useCallback(
    (key: string, params?: Record<string, string | number>) => {
      let text = translations[language]?.[key] || translations.en[key] || key;
      if (params) {
        for (const [k, v] of Object.entries(params)) {
          text = text.replace(`{${k}}`, String(v));
        }
      }
      return text;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export { LanguageContext };
